version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - net
  web_server:
    container_name: web_server
    build:
      context: ./web_server/
    ports:
      - "8000:8000"
    networks:
      - net
networks:
  net: